# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    pre: '<i class="fa fa-home"></i>&nbsp;'
    url: '/'
    weight: 10
  - name: Projets
    url: '/project'
    pre: '<i class="fas fa-users-gear"></i>&nbsp;'
    weight: 20
    identifier: projets
  - name: Blog
    url: '/post'
    pre: '<i class="fa fa-blog"></i>&nbsp;'
    weight: 30
    identifier: blog
  - name: Environnement
    url: '/project/environnement/'
    pre: '<i class="fa fa-seedling"></i>&nbsp;'
    weight: 10
    parent: projets
  - name: Ã‰ducation
    pre: '<i class="fa fa-graduation-cap"></i>&nbsp;'
    url: '/project/education'
    weight: 20
    parent: projets
  - name: SantÃ© & HygiÃ¨ne
    pre: '<i class="fa fa-shield-virus"></i>&nbsp;'
    url: '/project/sante-hygiene'
    weight: 30
    parent: projets
  - name: Jeunesse
    pre: 'ðŸš¸&nbsp;'
    url: '/project/jeunesse'
    weight: 40
    parent: projets
  - name: Entrepreneuriat
    pre: 'ðŸ’¡&nbsp;'
    url: '/project/entrepreneuriat'
    weight: 50
    parent: projets
  - name: Articles
    pre: '<i class="fa fa-feather-pointed"></i>&nbsp;'
    url: '/post'
    weight: 30
    parent: blog
  - name: Lâ€™Ã©quipe
    pre: '<i class="fa fa-user-group"></i>&nbsp;'
    url: '/#people'
    weight: 40
    parent: blog
  - name: Slides
    pre: 'ðŸ–µ&nbsp;'
    url: '/slides/example/'
    weight: 60
    parent: blog
  - name: Contact
    pre: '<i class="fa fa-envelope"></i>&nbsp;'
    url: '/#contact'
    weight: 60
